name: "Generate today's quiz"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  generate:
    name: "Generate today's quiz"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate
        run: make generate-todays-quiz

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate today's quiz"
          file_pattern: public/quiz/*.json

  publish:
    needs: generate
    uses: eddmann/name-that-aws-service/.github/workflows/publish.yml@main
