name: Publish

on:
  push:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: public
